global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9000'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'voter-profile'
    metrics_path: 'voter-profile/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8090'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Voter Profile'
  - job_name: 'voting-service'
    metrics_path: 'voting-service/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8091' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Voting Service'
  - job_name: 'result-aggregation'
    metrics_path: 'result-aggregation/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8092' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Result Aggregation'
  - job_name: 'polling-service'
    metrics_path: 'polling-service/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8093' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Polling Service'
  - job_name: 'ballot-service'
    metrics_path: 'ballot-service/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8094' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Ballot Service'
#  - job_name: 'order-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8081'] ## only for demo purposes don't use host.docker.internal in production
#        labels:
#          application: 'Order Service'
#  - job_name: 'inventory-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8082'] ## only for demo purposes don't use host.docker.internal in production
#        labels:
#          application: 'Inventory Service'
#  - job_name: 'notification-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8083'] ## only for demo purposes don't use host.docker.internal in production
#        labels:
#          application: 'Notification Service'